[project]
name = "files-transform"
version = "0.1.0"
description = "Simple example for cocoindex: transform files in a directory."
requires-python = ">=3.11"
dependencies = ["cocoindex>=1.0.0a9", "markdown-it-py[linkify,plugins]"]

[tool.uv]
prerelease = "explicit"

[tool.setuptools]
packages = []
