[package]
name = "cocoindex_core"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[dependencies]
cocoindex_utils = { path = "../utils" }

heed = "0.22.0"
storekey = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true, features = ["rc", "derive"] }
uuid = { workspace = true }
tokio = { workspace = true }
env_logger = { workspace = true }
bytes = { workspace = true }

rmp = { workspace = true }
rmp-serde = { workspace = true }
serde_with = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
