name: CI

on:
  pull_request:
    branches: [main, v1]
    paths:
      - rust/**
      - python/**
      - "*.toml"
      - ".github/workflows/*.yml"
  push:
    branches: [main, v1]
    paths:
      - rust/**
      - python/**
      - "*.toml"
      - ".github/workflows/*.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-test:
    name: Build & Test
    uses: ./.github/workflows/_test.yml
